spring.application.name=ChangelogGenerator
spring.datasource.url=jdbc:postgresql://localhost:5323/changelog-generator
spring.datasource.username=manjama
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=create
#drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

jwt.secret=MyVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
jwt.expiration=86400000

#Github OAuth
github.client.id=Ov23liWF0rqFz9oV8hKr
github.client.secret=637ea5b6b499197047c5c2bb71062c417947b37f
github.redirect.uri=http://localhost:8080/github/callback